### ISSUE TITLE
Homing anomoly

### ISSUE THREAD

**Issue by chschmit** [Silverquark/i3PlusPlus#11]
After a printjob is completed the head goes to the near edge of the Yaxis and the midpoint of the Xaxis. If I run a new printjob afterwards (without turning off the printer), the printer uses this endpoint as the new home position and will be off by about 60mm in the X axis.

My starting Gcode has a G28 code that worked great with the original Wanhao (Marlin 1.0) firmware. If I use the motor controls and press the Home | All button it seems to override this position and homes it's self based on the limits switches OR if I power-off/power-on the printer, my Gcode files (with G28) work normally.

It seems there may be something preventing the G28 code from being accepted.

**Comment by Silverquark** [comment]
Make sure you dont have a g92 in your end gcode

**Comment by chschmit** [comment]
I double-checked...My ending gcode does not have a G92 command.

Since it worked fine with the previous firmware, I was curious if the new firmware handles homing differently.

**Comment by Silverquark** [comment]
Hm. It's probably related to the marlin 1.1.x Firmware changes somehow. 
Had the same problem for a while but removing g92 from my end gcode fixed it for me. Will look into it

**Comment by chschmit** [comment]
Is the printing speed setting issue related to the new Marlin Firmware or something in the LCD firmware?

**Comment by vger74656** [comment]
I have the same issue mate... I have to tell Octoprint to send X and Y to home, then print, otherwise it hits the right side and grinds...

**Comment by jamesarm97** [comment]
Homing X after a print does not work. Tried stock firmware and I3Plus+ so it must be related to Marlin.

**Comment by Silverquark** [comment]
Closing this issue to merge it with a duplicate, will link to here in the other issue.
