### ISSUE TITLE
Touch dont working

### ISSUE THREAD

**Issue by leseaw** [Silverquark/i3PlusPlus#12]
Last release
Touch isnt working :(
Can do nothing .
Please help.

**Comment by Silverquark** [comment]
Try reinstalling both lcd and printer firmware. Doesnt it respond at all?
By that i mean if you press a button, does the color change?

**Comment by leseaw** [comment]
Display is brighter when you press something.
New design is visible, but without function.

And have done it twice already.

**Comment by Silverquark** [comment]
Make sure the serial cable is in correctly, sounds like it cant communicate with printer firmware
