### ISSUE TITLE
axis moving anomaly

### ISSUE THREAD

**Issue by Austinthemighty** [Silverquark/i3PlusPlus#16]
After turning on the printer, and hitting the move button to move one of the axes it tries to zero it and then moves it, which can cause the print head to hit a print or an object on the print bed.

**Comment by Silverquark** [comment]
Its intended behavior. It homes so it knows its coordinates. That way it can stop the printer from going out of bounds and crashing into the frame. Although i admit, its not a perfect solution and i will probably change it in the future

**Comment by Austinthemighty** [comment]
maybe save the z's hight to eprom
