### ISSUE TITLE
Auto PID for build plate for low temp (23 degrees) doesn't stop

### ISSUE THREAD

**Issue by phamtq** [Silverquark/i3PlusPlus#2]
When selecting the Auto PID for the build plate temp with a low one like 23 degrees, it continues on without stopping. There is also no cancel button/action to return to the previous menu. Using the Auto PID for the extruder temperature (tested at 188) works well and is done within 4 minutes.

**Comment by Silverquark** [comment]
Thx for reporting. Bed pid tuning is completely broken it seems. I will probably remove it for now since it's not really needed. Small temperature fluctuation in the bed are not really an issue anyway. Will try to fix it sometime in the future but it doesn't have high priority
