### ISSUE TITLE
Not Building

### ISSUE THREAD

**Issue by ill-tempered** [Silverquark/i3PlusPlus#27]
Master Branch is not building in Arduino software.

Hitting the below error:

Arduino: 1.8.4 (Mac OS X), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch/MarlinConfig.h:39:0,
                 from /***/i3PlusPlus-master/Marlin/Marlin.ino:31:
SanityCheck.h:609: error: #error "Z_MIN_PROBE_REPEATABILITY_TEST requires a probe: FIX_MOUNTED_PROBE, BLTOUCH, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or Z Servo."
   #error "Z_MIN_PROBE_REPEATABILITY_TEST requires a probe: FIX_MOUNTED_PROBE, BLTOUCH, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or Z Servo."
    ^
exit status 1
#error "Z_MIN_PROBE_REPEATABILITY_TEST requires a probe: FIX_MOUNTED_PROBE, BLTOUCH, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or Z Servo."

**Comment by Silverquark** [comment]
Whoops, forgot to comment something out. Fixed now
