### ISSUE TITLE
Thermal Runaway Error

### ISSUE THREAD

**Issue by entozoon** [Silverquark/i3PlusPlus#32]
I often, halfway through a print, get "Thermal Runaway Error", presumably because my bed temperature drops for more than 30 seconds (it actually drops like 10 degrees, no idea why).

So I'm thinking a solution might be if I could increase both values, in `/Marlin/Configuration_adv.h`
```
  #define THERMAL_PROTECTION_BED_PERIOD 30    // Seconds
  #define THERMAL_PROTECTION_BED_HYSTERESIS 3 // Degrees Celsius
```
Any tips on re-compiling this firmware? IDE, libraries, SDK, etc. I can't seem to find any info

**Comment by Silverquark** [comment]
Yeah these are the right values.
30 and 3 will mean that a thermal runaway arrow will occur when the temperature is off by over 3°C for 30 seconds. 
Conpiling is pretty straight forward. Just follow the steps under "using Arduino IDE" on the install instructions Page, here:
https://silverquark.github.io/i3PlusPlusSite/instructions.html
