### ISSUE TITLE
Stock LCD resources

### ISSUE THREAD

**Issue by raidzero** [Silverquark/i3PlusPlus#43]
How were the stock LCD resources pulled? I would like back up my Powerspec i3 plus LCD resources before diving into custom firmwares. Thanks!

**Comment by Silverquark** [comment]
The Stock lcd resources are from the official firmware releases from wanhao. And the Cocoon firmware, i got from their Support. I dont actually know if there is an easy way to pull the resources

**Comment by raidzero** [comment]
It sounds like you can wire up a serial cable and pull them. I was hoping you did this. Oh well, thanks for answering!
