### ISSUE TITLE
PID acting strange.

### ISSUE THREAD

**Issue by Tieya** [Silverquark/i3PlusPlus#8]
Cant get the auto PID from the LCD to work anymore it just locks up.
works fine from pc.

can anyone else confirm this issue or is it just me? (: 

Version: B2

**Comment by Silverquark** [comment]
No it's not just you. Beta 3 is coming today and will fix this and some other problems

**Comment by Tieya** [comment]
thanks Silver.

damn just updated 30min ago :P damn you!

nice work!

**Comment by Silverquark** [comment]
Sry,  im just human. Errors happen :D

**Comment by dl6abm** [comment]
still don't work for me in beta3 ...

**Comment by Silverquark** [comment]
Works fine here. What happens if you try it?
Some details would be nice to be able to help.
It takes a few minutes. It will display the temp graph while running and send you to a "done" screen after that

**Comment by dl6abm** [comment]
works fine now, don't know why it didn'start the first time.
First try was with the "not compiling version", where i fixed the code issue myself to get it compiling. 
Thanks for your ( and the other contributors) work!
rgds Holger
