### ISSUE TITLE
beta 3 doesn't compile, code broken line 811 to 813 in temperature.cpp

### ISSUE THREAD

**Issue by dl6abm** [Silverquark/i3PlusPlus#9]
guess it should be like in beta 2:

 #if HAS_THERMALLY_PROTECTED_BED
      thermal_runaway_protection(&thermal_runaway_bed_state_machine, &thermal_runaway_bed_timer, current_temperature_bed, target_temperature_bed, -1, THERMAL_PROTECTION_BED_PERIOD, THERMAL_PROTECTION_BED_HYSTERESIS);
    #endif

compiles after correction

**Comment by Silverquark** [comment]
fixed that in the release version. forgot to push to repo. should be fixed now.
